packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/cli': ^4.1.14
  '@tailwindcss/postcss': ^4.1.14
  '@tanstack/react-form': ^1.23.7
  '@tanstack/react-query': 5.90.5
  '@types/node': ^22.10.1
  eslint: ^9.37.0
  hono: ^4.10.4
  prettier: ^3.6.2
  tailwindcss: ^4.1.14
  typescript: ^5.9.3
  zod: ^3.23.8

catalogs:
  react19:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: 19.2.0
    react-dom: 19.2.0
